### ISSUE TITLE
Can I use a driving image instead of a driving video?

### ISSUE THREAD

**Issue by bernakabadayi** [bytedance/X-Portrait#6]
Hi, 

When I provide an image instead of a driving video, I realize that the method is not able to rotate the head very well and often outputs artifacts. I'm attaching samples of the source images, the driving images I used, and the output from X-Portrait. Do you have any tips to fix this? Thanks!

![009_ref](https://github.com/user-attachments/assets/8b0f3c0f-7c76-4fd0-81a8-8a5bb2896520)
![009_gt](https://github.com/user-attachments/assets/73559704-1dc5-46bd-ade5-636b46ce3c67)
![009_reenact](https://github.com/user-attachments/assets/7667df4f-0e27-4c72-8ed7-626b15020d64)

![002_ref](https://github.com/user-attachments/assets/b6767259-50aa-4fe8-9342-185f0081f73c)
![002_gt](https://github.com/user-attachments/assets/72c67ea9-11b8-4f55-9aa6-eb4d74a9ab61)
![002_reenact](https://github.com/user-attachments/assets/5153f6d2-2268-46bb-87ff-6c9878e7fd7c)

The command I used is that:

```
    python3 core.15637812.0/test_xportrait.py \
            --model_config config/cldm_v15_appearance_pose_local_mm.yaml \
            --output_dir /outputs \
            --resume_dir checkpoint/model_state-415001.th \
            --seed 999 \
            --uc_scale 5 \
            --source_image /dataset/009_ref.png \
            --driving_video /dataset/009_gt.mp4 \
            --best_frame -1 \
            --out_frames 0 \
            --num_mix 4 \
            --ddim_steps 30
```

**Comment by johndpope** [comment]
fyi - you maybe interested in this - https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait - if you're wanting to adjust the pose to specific head rotation.

**Comment by Janspiry** [comment]
Hi, how can I use the driving image rather than a video by modifying existing scripts?
